"Name: \TY:/IWCOR/CL_OD_EDM_PARAMETER\IN:/IWCOR/IF_OD_EDM_PARAMETER\ME:IS_NULLABLE\SE:END\EI
ENHANCEMENT 0 ZKSCC_ODATA_PARAM_NULLABLE.
  IF  me->mv_name = 'TranspOrdEvtNewExpDateTime'.
    rv_nullable = abap_true.
  ENDIF.
ENDENHANCEMENT.
